version: 2.1

orbs:
  heroku: circleci/heroku@1.2.6

commands:
  build-for-prod-command:
    steps:
      - checkout
      - run:
          name: install-packages
          command: npm install --production
  build-and-test-command:
    steps:
      - checkout
      - run:
          name: install-packages
          command: npm install
      - run:
          name: Run tests
          command: npm test

jobs:
  build-and-test:
    docker:
      - image: node:14.17.6
    steps:
      - build-and-test-command
  build-and-deploy:
    docker:
      - image: node:14.17.6
    steps:
      - build-for-prod-command
      - heroku/deploy-via-git

workflows:
  build-and-test:
    jobs:
      - build-and-test:
          filters:
            branches:
              ignore:
                - master
  build-and-deploy:
    jobs:
      - build-and-deploy:
          filters:
            branches:
              only:
                - master
