version: 2.1

jobs:
  run-tests:
    docker:
      - image: node:14.17.6
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          name: Run tests
          command: npm test

workflows:
  run-tests-workflow:
    jobs:
      - run-tests
