version: 2.1

orbs:
  heroku: circleci/heroku@1.2.6

jobs:
  build:
    docker:
      - image: node:14.17.6
    steps:
      - checkout
      - run:
          name: install-packages
          command: npm install
  test:
    docker:
      - image: node:14.17.6
    steps:
      - run:
          name: Run tests
          command: npm test

workflows:
  build-test-deploy:
    jobs:
      - build
      - test
      - heroku/deploy-via-git:
          filters:
            branches:
              only:
                - master
