version: 2.1

jobs:
  run-tests:
    docker:
      - image: node:14.17.6
    steps:
      - checkout
      - run:
          name: install-packages
          command: npm install
      - run:
          name: Run tests
          command: npm test

workflows:
  run-tests-workflow:
    jobs:
      - run-tests
